import WordCloud from './WordCloud.wc.svelte'
import Embeddings from './Embeddings.wc.svelte'
import Table from './Table.wc.svelte'
import Bar from './Bar.wc.svelte'
import BarGrid from './BarGrid.wc.svelte'
import Line from './Line.wc.svelte'